version: '3'

services:
  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1082:1080

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"

  app:
    build: ./docker/app
    container_name: docker_app
    restart: "always"
    volumes:
      - ./app:/var/www/html/app
      - ./logs/apache:/var/log/apache2
    ports:
      - 127.0.0.1:86:80
    links:
      - mysql
    depends_on:
      - mysql
    tty: true
    extra_hosts:
      # that's a default docker magic host's IP for containers to allow http request to itself by this hostname
      - "app.local:172.17.0.1"
    environment:
      ## Use webroot directory. i.e: /web for drupal scaffolding.
      WEB_ROOT: "/app"
      ## SSH support. Uncomment volumes -> # - ${SSH_AUTH_SOCK}:/ssh-agent
#      - SSH_AUTH_SOCK=/ssh-agent
      ### WARNING: Use only if you not use custom php.ini.
#      - PHP_SENDMAIL_PATH
#      - PHP_SENDMAIL_DOMAIN
#      - XDEBUG_ENABLED: "1"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'coffee'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
# Names our volume
volumes:
  mysql-db:
  esdata1:
    driver: local

networks:
  esnet:

